# Generated by Django 4.1.7 on 2023-07-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
