# Generated by Django 4.1.7 on 2023-07-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_id_user_user_id_text_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign',
            new_name='Sign_to_text',
        ),
        migrations.RenameModel(
            old_name='Text',
            new_name='Text_to_sign',
        ),
    ]
