# Generated by Django 4.1.7 on 2023-07-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_sign_sign_to_text_rename_text_text_to_sign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sign_to_text',
            table='Sign_to_text',
        ),
        migrations.AlterModelTable(
            name='text_to_sign',
            table='Text_to_sign',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
