# Generated by Django 4.1.7 on 2023-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sign_to_text_table_alter_text_to_sign_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_to_text',
            name='img_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='text_to_sign',
            name='text_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
