# Generated by Django 4.1.7 on 2023-07-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_product_review_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
