# Generated by Django 4.1.7 on 2023-07-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
