# Generated by Django 4.1.7 on 2023-07-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_to_text',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Sign_to_text',
            },
        ),
        migrations.CreateModel(
            name='Text_to_sign',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'Text_to_sign',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='text_to_sign',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='home.user'),
        ),
        migrations.AddField(
            model_name='sign_to_text',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='home.user'),
        ),
    ]
