# Generated by Django 4.1.7 on 2023-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sign_to_text_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_to_text',
            name='sign',
            field=models.ImageField(upload_to=''),
        ),
    ]
