# Generated by Django 4.1.7 on 2023-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_sign_to_text_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_to_text',
            name='sign',
            field=models.BinaryField(),
        ),
    ]
