# Generated by Django 4.1.7 on 2023-07-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_sign_to_text_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwd',
        ),
    ]
